import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import localFont from 'next/font/local';

const kollektif = localFont({
  src: './fonts/Kollektif.ttf',
  variable: '--font-kollektif',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kollektif.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
